css/suitcase.css
template.php
templates/region--branding.tpl.php
templates/region--search.tpl.php

Depends on suitcase_config [PR#2](https://github.com/isubit/suitcase_config/pull/2).

LUGG-763 : Support for suitcase_config variables

---

css/suitcase.css
templates/section--header.tpl.php

I put this in a new branch because I would like to make sure the black bar is accessible and nice before we merge it in with other code.
Things to look for:
Is the skip to content link still in a good place? Is the div structure terrible?

LUGG-851 Updated black bar

---

css/suitcase.css

Changed it from padding: 2px 3px to 10px

LUGG-913 Added padding to the search field

---

css/suitcase.css

Cleaned up CSS file a bit:
1. Removed old commented out code
2. Reorganized rules into meaningful clumps.
3. Reunited declarations that had been split u
4. Re-ordered properties within rules to be more consistent.
I didn’t actually change any CSS or try and simplify selectors.
Tested this on monarch and wildlife.

CSS Clean-Up

---

css/suitcase.css
css/suitcase_responsive.css

Breadcrumbs didn’t feel very breadcrumby. I tweaked the padding and text link styles to look more like breadcrumbs and feel more separate from the page content.

LUGG 920 - Restyling breadcrumbs

---

css/suitcase.css

- Put the news in a box
- Removed lines between news items
- Put the read more link inline
- Restyled the date

LUGG-922 Restyled news box and dates

---

css/suitcase.css

Restyled pagination and more-link buttons.

HHPN 109 - Pagination and More Links

---

css/suitcase.css

Restyled and positioned Prev/Next buttons to match pagers on other
types of pages.

LUGG-931 Restyled Events Prev/Nex to match other pagers

---

css/suitcase.css

Removed floats, and adjusted type styles.

LUGG-935 Restyled People category label

---

css/suitcase.css

Added border and padding, and adjusted alignment to improve usability of search result items.

LUGG-933 Restyle search results

---

css/suitcase.css

A wide variety of quick bug fixes and style tweaks for front page stuff.

LUGG 932 2

---

css/suitcase.css

Needed to nudge the title and +/- so they wouldn’t collide.

LUGG-934 Fix title colliding with +/-

---

css/suitcase.css

LUGG-934 Push the +/- back over

---

css/suitcase.css

A reset was breaking ul/ol in regular content.

LUGG-943 All ul/ol in .pane-content

---

css/suitcase.css

In the case of two blocks in the same panel and stuff needs to get cleared.

LUGG-942 Clearfix panel panes

---

css/suitcase.css

Removed extra rules that caused Events to look different from News.

LUGG-944 Match Events block to News block

---

css/suitcase.css

Targeting menus in the footer, which should suffice for now.

LUGG-940 Recolor social links in footer

---

css/suitcase.css

LUGG-939 Support for nested categories

---

css/suitcase.css

Added margin after li’s in .item-lists.

HHPN-118 Add spacing to .item-list items

---

css/suitcase.css

Fixed long content shrinking photos.

HHPN-119 Fixed long content shrinking photo

---

css/suitcase.css

I did some targeting to remove the border-bottom and resized the H2 for
having specific projects in a block.

BIED-9 Removed underlines and reduced heading size

---

css/suitcase.css
css/suitcase_responsive.css
template.php

Reformatting and restyling social links in both the footer and panel social menus, including brand hover colors.

INTERIM 14

---

css/suitcase.css

CSS to style a general button class for links.

INTERIM-16 Add general button class and styling

---

css/suitcase.css

Forced consistent styling for :focus state on links and form inputs.

INTERIM 18

---

css/suitcase.css

Removed CSS rule which was indenting paragraphs in panels

INTERIM-19 Removed CSS rule which was indenting paragraphs in panels

---

css/suitcase.css

Added styles for borders, padding, and a larger indicator.

INTERIM-9 New styles for collapsible fieldsets

---

ckeditor.css

Added a stylesheet specifically for ckeditor.
Testing:
- Pull down this branch
- Clear cache a lot
- Go to node/add and see if the font looks different. Also see if you can add a button class to a link and have it be styled like a button.

INTERIM-21 - Add stylesheet for ckeditor

---

css/suitcase.css

Styles for the blog block, author pic/name cards, the blog page, and
author page

INTERIM-22 Styling blog components to match Interim

---

css/suitcase.css

Removes borders from search bar

INTERIM-18 Removed border on search

---

css/suitcase.css

Reverts isubit/suitcase_interim#90

Revert "INTERIM-16 Add general button class and styling"

---

css/suitcase.css
js/suitcase_facet.js

New javascript and CSS to allow blocks to be open/closed by default, and a new more accessible way to hide content (absolute positioning).

WILE-18 Allow blocks to be set open/closed by default.

---

css/suitcase.css

Reverts isubit/suitcase_interim#112

Revert "INTERIM-35 Added indicator styling back in"

---

css/suitcase.css

Styles to accompany classes on HTML copy/paste templates to create image/links in Panels

INTERIM-34 Styles to accompany HTML image panel templates

---

css/suitcase.css

Styling here in the theme instead of the module.

LUGG-982 Styled content type indicators

---

css/suitcase.css

Borders were getting cut off on homepage panels.

LUGG-982 Overflow selector too leaky

---

css/suitcase.css
css/suitcase_responsive.css

INTERIM 26

---

css/suitcase.css

Added support for image link blocks, and included support for link text
to be p instead of only h2. Also made the link colors less leaky.

INTERIM-77 Support for image link blocks

---

css/suitcase.css
js/suitcase_responsive_tables.js

Add support for responsive Views tables

INTERIM-75 Responsive Views tables

---

css/suitcase.css

Tidied up styles for nested facets.

INTERIM 49

---

css/suitcase.css

Added back in CSS to float images in grid layouts.

INTERIM-48

---

css/suitcase.css

Also applied event cell styling to cells in week view.

NREM-216 Change white text in month view event cells

---

css/suitcase.css

I have looked for different image contexts, and I don't think it'll break anything.

EEOB-56 Helps images not squish as screen narrows

---

css/suitcase.css

To test: pull down a site with a video on the front page. Do the video margins match margins on other panel content? Does the video itself look squished or stretched?

CS-56 Fixed padding for video on panels

---

templates/region--isu_menu.tpl.php

Change all the sites in the ISU menu to use https instead of http.

LUGG-1053 Change ISU menu links to https

---

css/suitcase.css
template.php
templates/default_region_content_blocks/footer_third.tpl.php
templates/region--isu_menu.tpl.php
templates/section.tpl.php

Text and background color changes for the Day, Week, Month, and Year calendars for Events. Different color text appears on different color backgrounds in a variety of combinations, so used SiteImprove browser add-on to identify and fix them.
You should be able to use a well-populated Events calendar (like compsci), and run the SiteImprove checker, and there should be no contrast errors.

Interim 156

---

css/suitcase.css
panels/styles/add_class.inc
suitcase_interim.info

- Restyles Mega Panels to remove the borders from the Panel Regions. 
- Adds a Panels 'Style' that allows borders to be added back on in an individual basis.
Reminder: This will *not* affect Block styling, like Blocks just placed in Theme Regions.

INTERIM-163 Remove borders from Mega Panels

---

css/suitcase.css

There's been a want to adjust the alignment and spacing of various Views exposed filters, so this branch is hoping to clean those up so less tweaking is needed. It will need a bunch of testing with some attention paid to sites with custom styling modules.

Views exposed filters

---

css/suitcase.css
template.php

To test, add a LinkedIn link to the footer social media menu. 
**Confirm** a little square LinkedIn icon appears and that the hover color is LinkedIn blue.

LUGG-1203 Add LinkedIn
