isubit/suitcase_interim

css/suitcase.css
Changes:
Switched border-bottom to text-decoration: underline and removed hover effects in section-content. In the footer, links will be underlined but will change colors on hover (from gray to #C00).
=> LUGG-833 Change border-bottom to underlines

css/suitcase.css, template.php, templates/region--search.tpl.php
Currently, the search bar is hard coded into template.php. This means sites that don't use search or want to use some other search option have to use the solr search regardless.
I removed the search bar from template.php and from region--search.tpl.php. I re-added the button by using the background property in CSS.
I tested this on a local copy of the suitcase_luggage site.
- Pull down my changes
- Clear caches, etc.
- Add the "Search form" block to the "Search" region
- Go to the home page. Is the search form there?
- Add a site name/department name (so the header has 3 levels). Is there enough padding above the search bar?
- Only have the site name. Is there too much padding above the search bar?
- Double-check to see if the form is responsive.
- Does the search bar work?
=> LUGG-841 - Search bar should be a block

template.php
By default, Drupal will not mark menu items as active based on an absolute match of the page URL.
This is a problem when menu items are created with absolute URLs paths in order to preserve query strings.
This pull requests provides implementations of theme_links__system_main_menu and suitcase_interim_links__system_secondary_menu that will also mark an menu item as active if the menu link matches the full URL of the current page.
=> Mark menu items active if absolute url matches

css/suitcase.css, css/suitcase_responsive.css
Fixed links not wrapping, removed redundant text-align on mobile. Wasn’t allowed to make another branch with the same name as LUGG-914
=> LUGG 914 - Fixed secondary nav link wrapping, cleaned up text-align

css/suitcase.css
There was padding on some internal elements that caused elements like the heading and news items to not be lined up on the left. I removed the offending padding.
=> LUGG 918 - Lined up padding on homepage panels

css/suitcase.css
Added keyboard focus rules.
Big Question:
Should keyboard focus act the same as hovering your mouse over the link, but with outlines?
Should our outlines be the standard dotted line or the solid yellow border that I used?
Would appreciate detailed review, preferably taking edge case things into account (how it looks on non-standard views & whatnot).
=> LUGG-825 Added outlines on link focus

css/suitcase.css
The margin was pushing images outside of available space. Reducing the max-width to accommodate the margins keeps everything together.
=> DIGITALAG-11 Modified width on content images.

templates/default_region_content_blocks/footer_third.tpl.php
This needs to go [with the changes I made in luggage_ckeditor](https://github.com/isubit/luggage_ckeditor/pull/23).
Basically, testing this just needs to find out whether the current year displays when you automagically create new footer blocks.
=> LUGG-941 Added current year token to suitcase_interim block template

css/suitcase.css
Reverts isubit/suitcase_interim#81
Has site-specific styling, which should not be added in suitcase_interim.
=> Revert "HHPN-119 Fixed long content shrinking photo"

css/suitcase.css, css/suitcase_responsive.css
Contains pre-CSS refactor fixes for:
- Long URLs donking up resource view display
- URL padding in resource views
- People labels mush into their content on mobile
- The main menu gets covered up by flexslider slide labels
=> INTERIM-39 Mobile fixes

templates/default_region_content_blocks/footer_fourth.tpl.php, templates/default_region_content_blocks/footer_third.tpl.php, theme-settings.php
To test:
- Make sure the Social Menu and the default footer blocks don't exist on your test site
- Go to admin/appearance/settings/suitcase_interim and click the save button
- Go back to your site, double-check footer blocks. First and second should be the same, third should be social links and site map/index, and fourth should be copyright. Each of the social menu items should have a fontawesome icon.
=> INTERIM-44  Made footer more consistent with rest of university

templates/region--branding.tpl.php, theme-settings.php
By default, the wordmark should link to the site's homepage instead of www.iastate.edu
=> INTERIM-65 Change wordmark link default

css/suitcase.css
This rule catches text inputs not already styled more specifically,
like the content creation forms and search boxes.
=> HHPN-142 Padding and height were hiding input text

css/suitcase.css
Extra padding on these tr elements looked off when some views tables
went responsive.
=> INTERIM-76 Remove padding on tr

css/suitcase.css
Needs to be tested in IE 11. Check to see that the grid styling on views looks the same for IE11 as it does on other browsers (like on the luggage_people view). Should probably also see if there are regressions in other browsers.
=> INTERIM-82 Fixed flexbox in IE11

css/suitcase.css
The increased padding on node/add forms made luggage_people fields too big. This fixes that.
Review this by looking at each node/add form to make sure the form fields don't have unexpected wonkiness.
=> INTERIM-99 Removed right padding from node add fields

css/suitcase.css
Right now explicit heights set in the WYSIWYG may force some images to
warp when the window narrows. This is the responsive images fix.
=> NREM-211 Override explicit heights set so images can be responsive

css/suitcase.css
Started trying to fix taxonomy term styling and realized I was playing whack-a-mole. This is a bigger hammer, but should stop any new taxonomy vocabularies from being unstyled in the future.
To test:
- Pull down these changes, make sure you have events and news items on your site.
- Clear cache a bunch
- Look at one of your news items. How do news types look?
- Go to the news and event lists. How do taxonomy terms look there? Are they nice and styled like the taxonomy terms on news items/event pages?
- Make a new taxonomy and give it some terms. Add it to a content type. Make sure you change the display settings so that it shows on full page content with the same viewing options as other taxonomies (like categories and tags). Is it styled?
=> INTERIM-134 Made taxonomy styling selectors more general

preprocess/preprocess-region.inc, templates/form--system-theme-settings.tpl.php, templates/region--branding.tpl.php, theme-settings.php
Whilst subtheming Suitcase Interim, I found that that I could not change the logo, in any way, in my subtheme.  This is a result of Suitcase Interim's logo settings and displays being hardcoded to check against Suitcase Interim theme values explicitly.  This PR should fix that.
=> Interim 137

templates/region--isu_menu.tpl.php
This should change the Blackboard link to a Canvas link under the Sign-ons dropdown in the black ISU navbar.
=> LUGG-1052 Changed Blackboard link to Canvas link.

templates/section.tpl.php
This fixes our template issue by manually adding the missing div in. It should be tested on pages with blocks in the sidebar.
=> INTERIM-148 Updated template file to include the missing div

css/suitcase.css
To test: 
1. Create a Panels page using the Megapanels layout and make a rows of 2 items, 3 items, and 4 items.
2. In IE11, Safari, Chrome, and Firefox, do they behave like this?:
This had previously worked well in other browsers, so we want to make sure this fixes it in IE, and doesn't break it on the other browsers.
=> Interim 146 - IE fix for megapanels

css/suitcase.css
The hover and focus styles for the ISU Navbar should now look more as expected. When hovering or keyboard focusing on links in the ISU Navbar, they should have a lighter grey color.
=> INTERIM-150 Fix ISU Navbar hover and focus states

css/suitcase.css
This adjusts the link styling on the Announcement flexslider. 
Before: 
Desired After: 
To test: 
* Pull down this branch of Interim and make an Announcement flexslider with an *external* alternate url, and Caption.
I'm hoping the external link icon is gone, the link text is red, and is blue on hover.
=> LUGG-1070 Fix flexslider link styling, and remove external indicator.

template.php, templates/default_region_content_blocks/footer_third.tpl.php
This pull request changes i elements to span in generated blocks with fontawesome icons.
To test:
- pull down this pr on a local copy of a site
- if you're on an existing site, delete the footer blocks with fontawesome icons
- (re)save your theme settings to make new blocks
- check to make sure that the fontawesome icons show up properly, aren't missing closing tags, etc.
=> INTERIM-149 Change i elements to span

css/suitcase.css
A previous fix for panel wrapping was not compatible with Grow Panels. This fix should:
1. Allow rows of 3 and 4 panels to wrap properly, with any orphans not slamming out to full width.
2. Not allow Grow Panels to smush their sibling panels too small. They should look about 1/3 but they were being mushed to something more like 1/4.
=> WILE-48 Fix Grow Panel resize bug

css/suitcase.css
.item-list is used in many views to unstyle an unordered list, which is helpful. This selector was being too powerful and catching a elements that didn't need to be display block. This change *should* catch only the sort of "list of links" that it was intended for.
To test it, I must hunt around in different Views that are known to have links in unordered lists.
=> DIGITALAG-46 Leaky selector for item-list

preprocess/preprocess-section.inc, templates/section.tpl.php
We want to preserve the section element so that our pages make sense semantically. However, our section element needs an aria-label so screenreaders can tell why it's there. This pull request adds an aria-label to the main content section.
=> INTERIM-148 Add aria-label to content section

preprocess/preprocess-region.inc, templates/region--content.tpl.php, templates/region--isu_menu.tpl.php, templates/region--menu.tpl.php
This pull request should remove aria roles where they're not needed.
To test:
- pull down this branch
- run `drush registry-rebuild` and clear caches
- look over site pages with the siteimprove extension. do you still see the `Name, Role, Value 4.1.2` warnings?
- do you notice any new errors about missing roles or no-distinguishable landmarks??
=> INTERIM-151 Remove redundant WAI-ARIA attribute

templates/node.tpl.php
Right now, this conditional will always resolve to true even if there isn't content to render because the content links array isn't ever empty even when it isn't renderable. This means that we have an empty nav hanging out on all of our nodes, which is an accessibility issue. This pr changes the conditional to check whether or not the content links are renderable before attempting to put them on the page.
=> LUGG-1063 Check if content links are renderable

css/suitcase.css, panels/layouts/media_card/media-card.tpl.php
The [Media Card layout](https://github.com/isubit/suitcase_interim/wiki/Media-Card-Layout) had two nested divs, both with the `media-body` class. This could be a pain in the butt down the line.
=> INTERIM-166  Minor adjustments to the media card Display Suite layout

css/suitcase.css
To test:
- pull down branch
- add the `.panel-pane-overflow ` class to a panel block
- make some tall block content
- add some other blocks into the same row
- does the overflow content height match the other blocks' heights?
=> INTERIM-171 Make overflow pane taller

panels/layouts/suitcase_megapanels/suitcase_megapanels_admin.css
If Suitcase Interim was being used for admin pages, the layout of the Panes on the Layout screen of a Panel page was jumbled. This was because Suitcase Interim has extra CSS to actually style panels that don't work for the admin page. This change overrides those styles to make a simple grid.
=> INTERIM-175 Just in case Suitcase Interim is being used on admin pages.

css/suitcase.css, panels/layouts/suitcase_megapanels/suitcase-megapanels.tpl.php
See INTERIM-178 in Jira. Right now, blocks placed in the Top Full or Bottom Full panes in MegaPanels expand to touch the edge of the browser on narrow screens. That's not working out. 
This PR makes the padding the same as the other rows.
=> INTERIM-178 Adjust padding on the top and bottom full Mega Panels panes

css/suitcase.css
To Test:
1. Set up a luggage_bean_video
2. Choose a site that already has luggage_video modules in use
3. Switch Suitcase_Interim to   LUGG-1160 IN PROGRESS  
4. Are the luggage_video's working correctly? Are the black bars gone? Are they responsive?
5. Add a luggage_bean_video to a Panel page. Also working correctly still?
6. Try putting a luggage_bean_video in a mini-panel and put it in the content region of any node. This was where the bug appeared. Working?
=> LUGG-1160 Override luggage_video CSS for sizing videos

templates/zone--content.tpl.php
This affects the colored messages that show up at the top of the page when there's a warning, or to say you've successfully edited a page. They should now have ARIA role="status" which assistive technology can use.
=> LUGG-1165 Duplicate content template to add ARIA role to alerts.

ckeditor.css, css/suitcase.css
**To test:**
* Add `link-button` to the list of allowed classes in the WYSIWYG text formatter.
* Make a link in a page or something and add `link-button` to the Stylesheet Classes in the Advanced tab.
* Does the link look like a button in the CKEditor?
* Does the link look like a button in the published page?
=> INTERIM-29 Add a class to make a content link look like a button.

js/suitcase_responsive_tables.js
Right now, wide tables with colspan and rowspan are getting squished on mobile. We need them to just be themselves and horizontally scroll. This branch makes sure to strip out the responsive-table class which wasn't allowing them to do that. 
To test: 
1. Make a table with many columns and use rowspan or colspan (or both) in the table.
2. Narrow the window.
3. Can you view the whole table by scrolling it left/right?
4. Is the table scrunched up at all?
5. Test some regular tables. Do they get the nice responsive table treatment, still?
=> INTERIM-184 Remove the responsive-table class from colspan/rowspan tables

css/suitcase.css
There are a few rare cases when the external link indicator can wrap without its final word. 
1. If the link is in a table, the table cell doesn't account for the width of the external link indicator, so it will wrap without it. 
2. If the link contains a `p` element, such as in a luggage announcement caption. 
NOTE: Currently suitcase_interim excludes announcement links from the rule. But I fixed it anyway. 
To test: 
1. Pull down a suitcase_interim site
2. Make sure the external links javascript library is turned on under Appearance > Suitcase Interim > Settings > Advanced options > libraries tab
3. External link icons should wrap with the final word in the link.
=> INTERIM-186 Improve external link wrapping

css/suitcase.css
As seen in this ticket (discovered on music) the pause/play button is misaligned on Safari. This pull request should get them lined up again.
**To test:**
1. Find or make an announcements flexslider and add the flexslider-numbered class to the View
2. Make sure the flexslider is set to autoplay by checking the Slideshow box admin/config/media/flexslider/list/announcemant_slider/edit 
3. Make sure the buttons are all aligned on safari and other browsers.
HINT: music has one
Small fix but nice to mop up small things when we can.
=> INTERIM-179 Fix numbered flexslider button alignment on safari

ckeditor.css
Right now there are two minor issues with images and figures in CKeditor.
1. Text closely hugs images and figures floated left and right in CKeditor.
2. Figures (images with captions) smush when put in a table cell.
These changes to the CKeditor CSS file are meant to add some default spacing around floated images and stop figures from smushing. 
Refer to the ticket for the expected outcome: https://isubit.atlassian.net/browse/INTERIM-189
=> INTERIM-189 Adjusted sizing and spacing of images & figures in CKeditor

css/suitcase.css, js/suitcase_external_links.js
External links are tricky because they can occur in a variety of HTML structures. This branch should more comprehensively address them. The primary concern was that the icon would wrap to the next time on its own.
**To test:** 
Find ways to have an external link in multiple contexts.
These **should** have external link icons and they should look right and not be wrapping.
1. Link inline in text
2. Links in very narrow table columns. (You can dump a bunch of text in one column, and just a link in the second column.) 
3. Menu Cards with short link text and very long link text
These should **not** have external link icons.
1. Adventure Beans
2. Card Beans with and without an image
3. Hero Beans
4. Links in the site header and menu
5. Links in the footer
=> INTERIM-190 External link icon refactor
